[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["netlify:email"]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 4321
  port = 8888
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables (these should be set in Netlify dashboard)
[build.environment]
  NODE_ENV = "production"
  SITE_URL = "your-site-name.netlify.app"  # Replace with your actual Netlify site URL

[context.deploy-preview.environment]
  NODE_ENV = "development"
  SITE_URL = "deploy-preview-${DEPLOY_ID}--your-site-name.netlify.app"  # Replace with your actual Netlify site URL
